# Generated by Django 3.2.13 on 2022-05-24 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=512)),
                ('scenario', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=50, max_digits=100)),
                ('hurricane', models.DecimalField(decimal_places=50, max_digits=100)),
                ('flood', models.DecimalField(decimal_places=50, max_digits=100)),
                ('storm', models.DecimalField(decimal_places=50, max_digits=100)),
                ('wildfire', models.DecimalField(decimal_places=50, max_digits=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
